"""
Problem 2.Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""
from time_check import timer


@timer
def fibonacci_sum(num):
    result = 0
    a, b = 1, 2
    while a <= num:
        if a % 2 == 0:
            result += a
        a, b = b, a + b
    return result


if __name__ == "__main__":
    fibonacci_sum(4000000)
